### ISSUE TITLE
SQL INJECTION!

### ISSUE THREAD

**Issue by ronanyeah** [mohanagy/iLearn#14]
https://github.com/mohanagy/iLearn/blob/master/src/database/db.utiles.js#L15

**Comment by mohanagy** [comment]
[fixed](https://github.com/mohanagy/iLearn/commit/3bcc9bbdbe692581f7a72871e8171617af071cc0)

**Comment by ronanyeah** [comment]
Not fixed. There should be NO variables inside the query string. This can still be attacked.

**Comment by mohanagy** [comment]
the variables  not accessable  from outside

**Comment by mohanagy** [comment]
[fixed](https://github.com/mohanagy/iLearn/commit/9a197d0243546abf5e90e4b690927bb700106435)
